apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-31T12:32:45Z"
  generateName: katafygio-56dfc84769-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 56dfc84769
    release: katafygio
  name: katafygio-56dfc84769-4vlpv
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-56dfc84769
    uid: 2edef3b8-1d37-43dd-bcb2-7d840d968a3a
spec:
  containers:
  - args:
    - --local-dir=/var/lib/katafygio/data
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: tmp
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4445l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-4445l
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:32:45Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:32:45Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:32:45Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:32:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://86b322771c972b9ad42ab8d6ad2a2978842293aa737e71fd3b382ea728941766
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imageID: docker-pullable://svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio@sha256:8d6faaefcec1e94e2504b4c1e0b00d68bf34b223dac576dfea957c4bea928190
    lastState: {}
    name: katafygio
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-31T12:32:49Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.1.17
  podIPs:
  - ip: 10.244.1.17
  qosClass: BestEffort
  startTime: "2024-01-31T12:32:45Z"
